// Countdown
function updateCountdown() {
    const targetDate = new Date('2025-07-25T00:00:00');
    const now = new Date();
    const diff = targetDate - now;

    if (diff <= 0) {
        document.getElementById('timer').textContent = "Metrocon Day!";
        clearInterval(timerInterval);
        return;
    }

    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    const hours = Math.floor((diff / (1000 * 60 * 60)) % 24);
    const minutes = Math.floor((diff / (1000 * 60)) % 60);
    const seconds = Math.floor((diff / 1000) % 60);

    document.getElementById('timer').textContent =
        `${days}d ${hours}h ${minutes}m ${seconds}s`;
}

const timerInterval = setInterval(updateCountdown, 1000);
updateCountdown();

// --- BINGO LOGIC ---

const scavengerObjects = {
    leagueOfLegends: [
        "League of Legends",
        "Demacia",
        "Noxian",
        "Zaunite",
        "Vastaya",
        "Yordle",
        "K/DA",
        "Aatrox",
        "Ahri",
        "Akali",
        "Akshan",
        "Alistar",
        "Ambessa",
        "Amumu",
        "Anivia",
        "Annie",
        "Aphelios",
        "Ashe","Aurelion Sol","Aurora","Azir","Bard","Bel'Veth","Blitzcrank","Brand","Braum","Briar",
        "Caitlyn","Camille","Cassiopeia","Cho'Gath","Corki","Darius","Diana","Dr. Mundo","Draven","Ekko",
        "Elise","Evelynn","Ezreal","Fiddlesticks","Fiora","Fizz","Galio","Gangplank","Garen","Gnar",
        "Gragas","Graves","Gwen","Hecarim","Heimerdinger","Hwei","Illaoi","Irelia","Ivern","Janna",
        "Jarvan IV","Jax","Jayce","Jhin","Jinx","Kai'Sa","Kalista","Karma","Karthus","Kassadin",
        "Katarina","Kayle","Kayn","Kennen","Kha'Zix","Kindred","Kled","Kog'Maw","K'Sante","LeBlanc",
        "Lee Sin","Leona","Lillia","Lissandra","Lucian","Lulu","Lux","Malphite","Malzahar","Maokai",
        "Master Yi","Melio","Miss Fortune","Mordekaiser","Morgana","Naafiri","Nami","Nasus","Nautilus",
        "Neeko","Nidalee","Nilah","Nocturne","Nunu & Willump","Olaf","Orianna","Ornn","Pantheon","Poppy",
        "Pyke","Qiyana","Quinn","Rakan","Rammus","Rek'Sai","Rell","Renata Glasc","Renekton","Rengar",
        "Riven","Rumble","Ryze","Samira","Sejuani","Senna","Seraphine","Sett","Shaco","Shen",
        "Shyvana","Singed","Sion","Sivir","Skarner","Smolder","Sona","Soraka","Swain","Sylas",
        "Syndra","Tahm Kench","Taliyah","Talon","Taric","Teemo","Thresh","Tristana","Trundle","Tryndamere",
        "Twisted Fate","Twitch","Udyr","Urgot","Varus","Vayne","Veigar","Vel'Koz","Vex","Vi",
        "Viego","Viktor","Vladimir","Volibear","Warwick","Wukong","Xayah","Xerath","Xin Zhao","Yasuo",
        "Yone","Yorick","Yunara","Yuumi","Zac","Zed","Zeri","Ziggs","Zilean","Zoe","Zyra","Mel",
        "Arcane",
    ],
    valorant : [
        "Valorant",
        "Brimstone",
        "Viper",
        "Omen",
        "Killjoy",
        "Cypher",
        "Sova",
        "Skye",
        "Yoru",
        "Astra",
        "KAY/O",
        "Chamber",
        "Neon",
        "Fade",
        "Gekko",
        "Harbor",
        "Deadlock",
        "Iso",
        "Clove",
        "Vyse",
        "Tejo",
        "Waylay",
        "Jett",
        "Reyna",
        "Phoenix",
        "Raze"
    ],
    demonSlayer : [
        "Demon Slayer",
          // Protagonists & Companions
        "Tanjiro Kamado",
        "Nezuko Kamado",
        "Zenitsu Agatsuma",
        "Inosuke Hashibira",
        "Genya Shinazugawa",
        "Kanao Tsuyuri",

        // Hashira (Pillars)
        "Giyu Tomioka",       // Water Hashira
        "Shinobu Kocho",      // Insect Hashira
        "Kyojuro Rengoku",    // Flame Hashira
        "Tengen Uzui",        // Sound Hashira
        "Mitsuri Kanroji",    // Love Hashira
        "Obanai Iguro",       // Serpent Hashira
        "Sanemi Shinazugawa", // Wind Hashira
        "Muichiro Tokito",    // Mist Hashira
        "Gyomei Himejima",    // Stone Hashira
        "Kanae Kocho",        // (late) former Insect Hashira

        // Demons—Muzan’s Upper Moons and others
        "Muzan Kibutsuji",
        "Kokushibo",  // Upper Moon 1
        "Doma",       // Upper Moon 2
        "Akaza",      // Upper Moon 3
        "Hantengu",   // Upper Moon 4
        "Gyokko",     // Upper Moon 5
        "Daki",
        "Gyūtarō",    // Daki’s brother
        "Rui",
        "Kyōgai",
        "Susamaru",
        "Yahaba",
        "Hand Demon",
        "Temple Demon",
        "Swamp Demon",
        "Tongue Demon",
        "Fat Demon",
        "Spider Demon Father",
        "Spider Demon Mother",
        "Spider Demon Sister",
        "Spider Demon Brother",

        // Supporting human and demon-slayer side characters
        "Sakonji Urokodaki",
        "Sabito",
        "Makomo",
        "Murata",
        "Hotaru Haganezuka",
        "Aoi Kanzaki",
        "Kagaya Ubuyashiki",
        "Takeo Kamado",
        "Hanako Kamado",
        "Shigeru Kamado",
        "Rokuta Kamado",
        "Sumihiko Kamado", // descendant in modern story arc
        "Yushiro",

    ],
    jujutsuKaisen: [
        "Jujutsu Kaisen",
        // Tokyo Jujutsu High students & staff
        "Yuji Itadori", "Megumi Fushiguro", "Nobara Kugisaki",
        "Satoru Gojo", "Maki Zenin", "Toge Inumaki", "Panda",
        "Yuta Okkotsu", "Kinji Hakari", "Kirara Hoshi",
        "Shoko Ieiri", "Masamichi Yaga", "Atsuya Kusakabe",
        "Kiyotaka Ijichi", "Akari Nitta",

        // Kyoto Jujutsu High
        "Aoi Todo", "Noritoshi Kamo", "Momo Nishimiya",
        "Mai Zenin", "Ultimate Mekamaru", "Kasumi Miwa",
        "Arata Nitta", "Yoshinobu Gakuganji", "Utahime Iori",

        // Other Jujutsu Sorcerers
        "Kento Nanami", "Takuma Ino", "Mei Mei", "Ui Ui",
        "Yuki Tsukumo", "Tengen", "Naobito Zenin",
        "Naoya Zenin", "Ogi Zenin", "Jinichi Zenin",

        // Curse Users & Allies
        "Suguru Geto", "Uraume", "Ogami (grandma)", "Mago",
        "Jiro Awasaka", "Haruta Shigemo",

        // Cursed Spirits & Death Paintings
        "Ryomen Sukuna", "Mahito", "Jogo",
        "Choso", "Rika Orimoto",

        // Supporting / background characters
        "Riko Amanai", "Misato Kuroi", "Shiu Kong", "Yu Haibara",
        "Larue", "Manami Suda", "Toshihisa Negi",
        "Mimiko Hasaba", "Nanako Hasaba", "Miguel Oduor",
        "Tsumiki Fushiguro", "Hiromi Higuruma", "Fumihiko Takaba",
        "Reggie Star", "Hana Kurusu", "Ryu Ishigoori",
        "Takako Uro", "Hagane Daido", "Toji Fushiguro",
        "Wasuke Itadori", "Junpei Yoshino", "Yuko Ozawa"
    ],
    onePiece: [
        "One Piece",
        "Monkey D. Luffy",
        "Roronoa Zoro",
        "Nami",
        "Usopp",
        "Sanji",
        "Tony Tony Chopper",
        "Nico Robin",
        "Franky",
        "Brook",
        "Jinbe",
        // Yonko & Pirate Emperors
        "Shanks", "Big Mom", "Kaido", "Blackbeard",
        // Warlords & Major Villains
        "Crocodile", "Donquixote Doflamingo", "Dracule Mihawk", "Boa Hancock",
        "Buggy the Clown", "Arlong", "Don Krieg", "Captain Kuro",
        // Revolutionary Army
        "Monkey D. Dragon", "Sabo", "Ivankov",
        // Marine Admirals / Government
        "Sakazuki (Akainu)", "Kuzan (Aokiji)", "Kizaru", "Fujitora",
        "Garp", "Tsuru",
        // Worst Generation & Supernovas
        "Trafalgar D. Water Law", "Eustass Kid", "Killer", "Scratchmen Apoo",
        "Jewelry Bonney", "Basil Hawkins",
        // Early Allies & Supporting Characters
        "Vivi", "Kaya", "Dr. Kureha", "Hiriluk",
        "Helmeppo", "Koby",
        "Bartolomeo",
        "Edward Newgate",
        "Whitebeard",
        "Straw Hat",
        "Straw Hat Pirates",
        "Portgas D. Ace",
    ],
    attackOnTitan: [
        "Eldian", "Marleyan", "Subjects of Ymir",
          // 104th Training Corps & Main Trio
        "Eren Yeager", "Mikasa Ackerman", "Armin Arlert",
        "Jean Kirstein", "Connie Springer", "Sasha Blouse",
        "Krista Lenz", "Historia Reiss", "Ymir", "Annie Leonhart",
        "Marco Bott",
        
        // Survey Corps Leadership & Scouts
        "Levi Ackerman", "Erwin Smith", "Hange Zoë", "Dot Pixis",
        "Mike Zacharias", "Petra Ral", "Eld Jinn", "Oluo Bozado",
        "Gunther Schultz", "Nanaba", "Moblit Berner", "Floch Forster",
        "Marlowe Freudenberg", "Keith Shadis", "Dimitri Zackly",
        
        // Garrison & Military Police
        "Rico Brzenska", "Hannes", "Ian Dietrich", "Kitz Weilman",
        "Nile Dok", "Hitch Dreyse",
        
        // Reiss / Royal Family & Paradis Eldians
        "Carla Yeager", "Grisha Yeager", "Kuchel Ackerman",
        "Rod Reiss", "Uri Reiss", "Frieda Reiss", "Historia Reiss",
        "Ymir Fritz", "Erd Reiss",
        
        // Marley Warriors & Eldians
        "Reiner Braun", "Bertolt Hoover", "Zeke Yeager",
        "Pieck Finger", "Porco Galliard", "Falco Grice",
        "Gabi Braun", "Colt Grice", "Udo", "Zofia", "Theo Magath",
        "Yelena",
        
        // Titan Shifters / Major Titans
        "Attack Titan", "Armored Titan", "Colossal Titan",
        "Beast Titan", "Female Titan", "Cart Titan", "Jaw Titan",
        "War Hammer Titan", "Founding Titan",
        
        // Additional Notables
        "Kenny Ackerman", "Yelena",
        "Attack on Titan",  
  
        "Armored",
        "Beast",
        "Cart",
        "Colossus",
        "Female",
        "Male",
        "Titan",
    ],
    myHeroAcademia: [
        "My Hero Academia",
        // Class 1-A Students (U.A. High)
        "Izuku Midoriya",
        "Katsuki Bakugo",
        "Shoto Todoroki",
        "Ochaco Uraraka",
        "Tenya Iida",
        "Eijiro Kirishima",
        "Toru Hagakure",
        "Fumikage Tokoyami",
        "Hanta Sero",
        "Minoru Mineta",
        "Momo Yaoyorozu",
        "Kyoka Jiro",
        "Mezo Shoji",
        "Rikido Sato",
        "Koji Koda",
        "Denki Kaminari",
        "Mashirao Ojiro",
        "Tsuyu Asui",
        "Mina Ashido",
        "Yuga Aoyama",

        // Notable Other Students (Class 1-B, Shiketsu & support)
        "Hitoshi Shinso",
        "Mei Hatsume",
        "Mirio Togata",
        "Tamaki Amajiki",
        "Nejire Hado",
        "Inasa Yoarashi",

        // U.A. Staff & Pro Heroes
        "All Might",
        "Endeavor",
        "Hawks",
        "Best Jeanist",
        "Eraser Head (Shota Aizawa)",
        "Sir Nighteye",
        "Fat Gum",
        "Present Mic",
        "Ryukyu",
        "Gang Orca",
        "Mirko",

        // League of Villains, Meta Liberation & Paranormal Liberation Front
        "Tomura Shigaraki",
        "All For One",
        "Dabi",
        "Himiko Toga",
        "Twice",
        "Spinner",
        "Mr. Compress",
        "Kurogiri",
        "Gigantomachia",
        "Dr. Kyudai Garaki (Daruma Ujiko)",
        "Overhaul (Kai Chisaki)",
        "Re-Destro (Rikiya Yotsubashi)",
        "Stain",
        "Mustard",
        "Moonfish",
        
        // Supporting Characters & Civilians
        "Eri",
        "Kota Izumi",
        "Danjuro Tobita (Gentle Criminal)",
        "Kaina Tsutsumi (Lady Nagant)"
    ],
    spyXFamily: [
        "Spy x Family",
        "Loid Forger",
        "Yor Forger",
        "Anya Forger",
    ],
    neonGenesisEvangelion: [
        "Neon Genesis Evangelion",
        "Asuka Langley Soryu",
        "Rei Ayanami",
    ],
    yuYuHakusho: [
        "YuYu Hakusho",
        "Kazuma Kuwabara",
        "Yusuke Urameshi",
        "Hiei",
    ],
    theBoys: [
        "The Boys",
        "Homelander",
    ],
    fairyTail: [
        "Fairy Tail",
        "Natsu Dragneel",
        "Lucy Heartfilia",
        "Juvia Lockser",
    ],
    dragonBall: [
        "Dragon Ball",
        "Dragon Ball GT",
        "Dragon Ball Z",
        "Dragon Ball Super",
        "Dragon Ball Daima",
        "Red Ribbon Army",
        // Protagonists & Saiyan Family
        "Goku", "Super Saiyan Goku", "Kaioken Goku", "Super Saiyan 2 Goku", "Super Saiyan 3 Goku", "Super Saiyan 4 Goku", "Super Saiyan God Goku", "Super Saiyan Blue Goku", "Super Saiyan God Super Saiyan Goku", "Super Saiyan Blue Kaioken Goku", "Ultra Instinct Goku", "Great Ape", "Great Ape Goku", "Base Form Goku",
        "Vegeta", "Super Saiyan Vegeta", "Kaioken Vegeta", "Super Saiyan 2 Vegeta", "Super Saiyan 3 Vegeta", "Super Saiyan 4 Vegeta", "Super Saiyan God Vegeta", "Super Saiyan Blue Vegeta", "Super Saiyan God Super Saiyan Vegeta", "Ultra Ego Vegeta", "Great Ape Vegeta", "Majin Vegeta", "Base Form Vegeta", "Super Saiyan Blue Evolution Vegeta",
        "Baby", "Super Baby",
        "Vegito", "Super Vegito", "Super Saiyan Blue Vegito",
        "Gogeta", "Super Gogeta", "Super Saiyan Blue Gogeta",
        "Gohan", "Super Saiyan Gohan", "Super Saiyan 2 Gohan", "Beast Gohan", "Kid Gohan", "Teen Gohan",
        "Goten", "Super Saiyan Goten", "Super Saiyan 2 Goten",
        "Gotenks", "Super Saiyan 3 Gotenks",
        "Trunks", "Kid Trunks", "Super Saiyan Trunks", "Super Saiyan 2 Trunks", "Future Trunks",
        "Pan", "Bardock", "Super Saiyan Bardock", "King Vegeta",
        // Z‑Warriors / Allies
        "Krillin", "Tien Shinhan", "Yamcha", "Master Roshi", "Chiaotzu", "Yajirobe",
        "Piccolo", "Orange Piccolo", "Bulma", "Chi‑Chi", "Oolong", "Puar", "Yamcha", "Ox‑King",
        // Androids & Cyborgs
        "Android 8", "Android 16", "Android 17", "Android 18", "Android 19", "Android 20 (Dr. Gero)", "Android 21",
        // Major Villains
        "Frieza", "First Form Frieza", "Second Form Freiza", "Third Form Frieza", "Final Form Frieza", "Mecha Frieza", "Golden Frieza",
        "King Cold", "Cooler", "Final Form Cooler", "Meta-Cooler", "Cell", "Imperfect Cell", "Semi-Perfect Cell", "Perfect Cell", "Super Perfect Cell", "Cell Jr.", 
         "Majin Buu", "Fat Buu", "Evil Buu", "Super Buu", "Babidi", "Dabura",
        "Janemba", "Hirudegarn", "Lord Slug",
        // Ginyu Force
        "Captain Ginyu", "Recoome", "Jeice", "Burter", "Guldo",
        // Namekians & Namek Saga
        "Kami", "Nail", "Dende", "King Piccolo", "Tambourine", "Drum", "Piano",
        // Gods & Supreme Kais
        "Beerus", "Whis", "Supreme Kai", "Old Kai", "Grand Minister", "Zeno", "Grand Priest", "Grand Minister",

        // Universe Survival Saga (DB Super)
       "Super Saiyan Caulifla", "Berserker Kale", "Kefla", "Super Saiyan Cabba", "Super Saiyan 2 Cabba",
        "God of Destruction Toppo", "God of Destruction",
        "Universe 2 God of Destruction Heles",
        "Universe 2 Angel Sour",
        "Universe 3 God of Destruction Mosco",
        "Universe 3 Angel Camparri",
        "Universe 4 God of Destruction Quitela",
        "Universe 4 Angel Cognac",
        "Universe 5 God of Destruction Arak",
        "Universe 5 Angel Cukatail",
        "Universe 6 God of Destruction Champa",
        "Universe 6 Angel Vados",
        "Universe 8 God of Destruction Liquiir",
        "Universe 8 Angel Korn",
        "Universe 9 God of Destruction Sidra",
        "Universe 9 Angel Mojito",
        "Universe 10 God of Destruction Rumsshi",
        "Universe 10 Angel Cus",
        "Universe 11 God of Destruction Belmod",
        "Universe 11 Angel Marcarita",
        "Universe 12 God of Destruction Giin",
        "Universe 12 Angel Martinu",
        // Other notable characters
        "Goku Black", "Fused Zamasu", "Vegito", "Gogeta", "Omega Shenron", "Zamasu", "Goku Rose",
        "Kid Goku",
        "Android",
        "Videl",
        "Broly",
        "Super Broly",
        "Ginyu Force",
        "Kaioken",
        "Legendary Super Saiyan",
        "Super Saiyan",
        "Super Saiyan 2",
        "Super Saiyan 3",
        "Super Saiyan 4",
        "Super Saiyan God",
        "Super Saiyan God Super Saiyan",
        "Super Saiyan Blue",
        "Half-Saiyan",
        "Saiyan",
        "Frieza Race",
        "Frieza Clan",
        "Frieza's Army",
        "Universe 6",
        "Earthling",
        "Universe 7",
        "Universe 7",
        "Namekian",
        "Great Saiyaman",
        "Universe 2",
        "Universe 3",
        "Universe 4",
        "Universe 9",
        "Universe 10",
        "Universe 11",
          // Universe 2
        "Ribrianne", "Kakunsa", "Rozie", "Harmira", "Rabanra", "Zarbuto", "Zirloin", "Jimizu", "Bikal", "Prum",

        // Universe 3
        "Paparoni", "Nigrissi", "Pancea", "Koitsukai", "Narirama", "Biara", "Borareta", "Catopesra",
        "Maji‑Kayo", "Za Priccio",

        // Universe 4
        "Ganos", "Caway", "Shantza", "Damom", "Nink", "Majora", "Shosa", "Gamisalas", "Dercori", "Monna",

        // Universe 6
        "Cabba", "Hit", "Frost", "Auta Magetta", "Rota", "Caulifla", "Kale", "Saonel", "Pirina", "Botamo",

        // Universe 9
        "Bergamo", "Basil", "Lavender", "Sorrel", "Hop", "Hyssop", "Chappil", "Oregano", "Roselle", "Comfey",

        // Universe 10
        "Murichim", "Obni", "Dyrasem", "Rylibeu", "Murisam", "Napapa", "Zircor", "Dium", "Rubalt", "Methiop",

        // Universe 11
        "Jiren", "Toppo", "Dyspo", "Casserale", "K'nsi", "Tupper", "Cocotte", "Zoire", "Kettle", "Vewon",
    ],
    mortalKombat: [
        "Mortal Kombat",
        "Scorpion",
        "Sub‑Zero",
        "Liu Kang",
        "Raiden",
        "Johnny Cage",
        "Sonya Blade",
        "Kung Lao",
        "Kitana",
        "Mileena",
        "Jax Briggs",
        "Kano",
        "Shang Tsung",
        "Shao Kahn",
        "Reptile",
        "Smoke",
        "Noob Saibot",
        "Ermac",
        "Baraka",
        "Kabal",
        "Jade",
        "Sektor",
        "Cyrax",
        "Nightwolf",
        "Rain",
        "Skarlet",
        "Sindel",
        "Quan Chi",
        "Tanya",
        "Kenshi",
        "Frost",
        "Goro",
        "Havik",
        "Li Mei",
        "Ermac",
        "Reiko",
        "Sareena",
        "D'Vorah",
        "Erron Black",
        "Cassie Cage",
        "Jacqui Briggs",
        "Kotal Kahn",
        "Ferra/Torr",
        "Takeda Takahashi",
        "Bo' Rai Cho",
        "Mavado",
        "Motaro",
        "Shujinko",
        "Hotaru",
        "Dairou",
        "Drahmin",
        "Onaga",
        "Daegon",
        "Taven",
        "Dark Kahn",
        "Cyrax",
        "Khameleon",
        "Predator",
        "Jason Voorhees",
        "Tarkatan Xenomorph"
    ],
    overwatch: [
        "Overwatch",
        "Ana", "Ashe", "Baptiste", "Bastion", "Brigitte",
        "Cassidy", "D.Va", "Doomfist", "Echo", "Genji",
        "Hanzo", "Hazard", "Illari", "Junker Queen", "Junkrat",
        "Juno", "Kiriko", "Lifeweaver", "Lúcio", "Mauga",
        "Mei", "Mercy", "Moira", "Orisa", "Pharah",
        "Ramattra", "Reaper", "Reinhardt", "Roadhog", "Sigma",
        "Sojourn", "Soldier: 76", "Sombra", "Symmetra", "Torbjörn",
        "Tracer", "Venture", "Widowmaker", "Winston", "Wrecking Ball",
        "Zarya", "Zenyatta"
    ],
    hunterXHunter: [
        "Hunter x Hunter",
        "Killua Zoldyck",
        "Hisoka",
        "Gon Freecss",
        "Kurapika",
    ],
    bleach: [
        "Bleach",
        "Ichigo Kurosaki",
        "Rukia Kuchiki",
        "Orihime Inoue",
        "Uryū Ishida",
        "Yasutora 'Chad' Sado",
        "Renji Abarai",
        "Byakuya Kuchiki",
        "Tōshirō Hitsugaya",
        "Rangiku Matsumoto",
        "Kenpachi Zaraki",
        "Yachiru Kusajishi",
        "Shunsui Kyōraku",
        "Jūshirō Ukitake",
        "Sōsuke Aizen",
        "Gin Ichimaru",
        "Kaname Tōsen",
        "Mayuri Kurotsuchi",
        "Nemu Kurotsuchi",
        "Retsu Unohana",
        "Isane Kotetsu",
        "Shinji Hirako",
        "Kisuke Urahara",
        "Yoruichi Shihōin",
        "Isshin Kurosaki",
        "Ryūken Ishida",
        "Kūkaku Shiba",
        "Kaien Shiba",
        "Sajin Komamura",
        "Ikkaku Madarame",
        "Yumichika Ayasegawa",
        "Lisa Yadōmaru",
        "Love Aikawa",
        "Hachigen Ushōda",
        "Mashiro Kuna",
        "Rōjūrō Ōtoribashi",
        "Hiyori Sarugaki",
        "Coyote Starrk",
        "Baraggan Louisenbairn",
        "Tier Harribel",
        "Ulquiorra Cifer",
        "Nnoitra Gilga",
        "Grimmjow Jaegerjaquez",
        "Szayelaporro Granz",
        "Aaroniero Arruruerie",
        "Zommari Rureaux",
        "Yammy Llargo",
        "Neliel Tu Odelschwanck",
        "Pesche Guatiche",
        "Dondochakka Bilstin",
        "Lilynette Gingerbuck",
        "Jugram Haschwalth",
        "Yhwach",
        "Bambietta Basterbine",
        "Askin Nakk Le Vaar",
        "Bazz-B",
        "Liltotto Lamperd",
        "Giselle Gewelle",
        "Pernida Parnkgjas",
        "Gerard Valkyrie",
        "Uryū Ishida (Wandenreich)"
    ],
    konoSuba: [
        "KonoSuba",
        "Kazuma Sato",
        "Aqua",
        "Megumin",
        "Darkness",
    ],
    naruto: [
        "Boruto",
        "Rasengan",
        "Chidori",
        "Naruto",
        "Naruto Uzumaki",
        "Sasuke Uchiha",
        "Sakura Haruno",
        "Kakashi Hatake",
        "Madara Uchiha",
        "Obito Uchiha",
        "Tobi",
        "Kaguya Ōtsutsuki",
        "Nagato",
        "Pain",
        "Kabuto Yakushi",
        "Orochimaru",
        "Zabuza Momochi",
        "Haku",
        "Hinata Hyuga",
        "Shikamaru Nara",
        "Rock Lee",
        "Neji Hyuga",
        "Choji Akimichi",
        "Ino Yamanaka",
        "Kiba Inuzuka",
        "Shino Aburame",
        "Tenten",
        "Might Guy",
        "Asuma Sarutobi",
        "Kurenai Yuhi",
        "Iruka Umino",
        "Yamato",
        "Sai",
        "Tsunade Senju",
        "Hiruzen Sarutobi",
        "Minato Namikaze",
        "Hashirama Senju",
        "Tobirama Senju",
        "Gaara",
        "Itachi Uchiha",
        "Killer Bee",
        "Kurama",
        "Nine-Tails",
        "Deidara",
        "Sasori",
        "Kisame Hoshigaki",
        "Hidan",
        "Kakuzu",
        "Konan",
        "Jiraiya",
        "Rin Nohara",
        "Danzo Shimura",
        "Sharingan",
        "Mangekyō Sharingan",
        "Byakugan",
        "Rinnegan",
        "Akatsuki",
    ],
    fireEmblem: [
        "Fire Emblem",
        "Marth",
        "Roy",
        "Lyn",
        "Lucina",
        "Tiki",
        "Ike",
        "Chrom",
        "Corrin",
        "Black Knight",
        "Byleth",
        "Hubert von Vestra",
        "Ferdinand von Aegir",
        "Linhardt von Hevring",
        "Caspar von Bergliez",
        "Bernadetta von Varley",
        "Dorothea Arnault",
        "Petra Macneary",
        "Felix Hugo Fraldarius",
        "Sylvain Jose Gautier",

        // Blue Lions House
        "Dimitri Alexandre Blaiddyd",
        "Dedue Molinaro",
        "Felix Hugo Fraldarius",
        "Mercedes von Martritz",
        "Ashe Ubert",
        "Annette Fantine Dominic",
        "Sylvain Jose Gautier",
        "Ingrid Brandl Galatea",
        "Ignatz Victor",
        "Lorenz Hellman Gloucester",

        // Golden Deer House
        "Claude von Riegan",
        "Hilda Valentine Goneril",
        "Lorenz Hellman Gloucester",
        "Raphael Kirsten",
        "Lysithea von Ordelia",
        "Marianne von Edmund",
        "Ignatz Victor",

        // Faculty and Administration
        "Rhea",
        "Seteth",
        "Flayn",
        "Gilbert",
        "Jeralt Reus Eisner",
        "Catherine",
        "Shamir Nevrand",
        "Sothis",

        // Other Important Characters
        "Crest of Flames",
        "Ash",
        "Catherine",
        "Shamir Nevrand"
    ],
    warhammer: [
        "Warhammer",
        "Warhammer 40K",
        "Space Marines",
        "Chaos Knights",
        "Tyranids",
        "Thousand Sons",
        "Chaos Space Marines",
        "Tyranids",
        "Necrons",
        "Orks",
        "Chaos Daemons",
        "Genestealer Cults",
        "Leagues of Votann",
        "Roboute Guilliman",
        "The Emperor of Mankind",
        "Horus Lupercal",
        "Sanguinius",
        "Magnus the Red",
        "Leman Russ",
        "Lion El'Jonson",
        "Rogal Dorn",
        "Perturabo",
        "Mortarion",
        "Konrad Curze",
        "Angron",
        "Jaghatai Khan",
        "Fulgrim",
        "Alpharius Omegon",
        "Abaddon the Despoiler",
        "Belisarius Cawl",
        "Trazyn the Infinite",
        "Szarekh, the Silent King",
        "Commander Farsight",
        "Ghazghkull Mag Uruk Thraka",
        "Saint Celestine",
        "Inquisitor Eisenhorn",
        "Yvraine",
        "Kaldor Draigo",
        "Typhus",
        "Lucius the Eternal",
        "Khârn the Betrayer",
        "Fabius Bile"
    ],
    reZero: [
        "Re:Zero",
        "Emilia",
        "Rem",
        "Ram",
        "Subaru Natsuki",
    ],
    superMario: [
        "Super Mario",
        "Mario Kart",
        "Bowsette",
        "Peach",
        "Daisy",
        "Mario",
        "Luigi",
        "Princess Peach",
        "Princess Daisy",
        "Yoshi",
        "Toad",
        "Toadette",
        "Rosalina",
        "Bowser",
        "Bowser Jr.",
        "Donkey Kong",
        "Diddy Kong",
        "Wario",
        "Waluigi",
        "Koopa Troopa",
        "Dry Bones",
        "Boo",
        "King Boo",
        "Goomba",
        "Shy Guy",
        "Lakitu",
        "Hammer Bro",
        "Monty Mole",
        "Kamek",
        "Birdo",
        "Petey Piranha",
        "Chain Chomp",
        "Nabbit",
        "Spike",
        "Bob-omb",
        "Fawful",
        "Cappy",
        "Pauline",
        "Plessie",
        "Lubba",
        "E. Gadd",
        "Baby Mario",
        "Baby Luigi",
        "Baby Peach",
        "Baby Daisy",
        "Baby Rosalina",
        "Metal Mario",
        "Pink Gold Peach",
        "Dry Bowser",
        "Luma",
        "Iggy",
        "Ludwig",
        "Larry",
        "Wendy",
        "Morton",
        "Roy"
    ],
    avatarTheLastAirbender: [
        "Avatar: The Last Airbender",
        "Air Bender",
        "Earth Bender",
        "Blood Bender",
        "Water Bender",
        "Fire Bender",
        "Aang",
        "Zuko",
        "Katara",
        "Toph Beifong",
        "Azula",
        "Sokka",
        "Uncle Iroh",
        "Appa",
        "Suki",
        "King Bumi",
        "Admiral Zhao",
        "Korra",
    ],
    superSmashBrosUltimate: [
        "Super Smash Bros. Ultimate",
        "Donkey Kong",
        "Dark Samus",
        "Kirby",
        "Fox",
        "Ness",
        "Captain Falcon",
        "Jigglypuff",
        "Bowser",
        "Ice Climbers",
        "Sheik",
        "Zelda",
        "Dr. Mario",
        "Pichu",
        "Falco",
        "Young Link",
        "Ganondorf",
        "Mr. Game & Watch",
        "Meta Knight",
        "Pit",
        "Dark Pit",
        "Zero Suit Samus",
        "Snake",
        "Pokémon Trainer",
        "Diddy Kong",
        "Lucas",
        "King Dedede",
        "Olimar",
        "Lucario",
        "R.O.B.",
        "Toon Link",
        "Wolf",
        "Villager",
        "Mega Man",
        "Wii Fit Trainer",
        "Rosalina & Luma",
        "Little Mac",
        "Greninja",
        "Mii Brawler",
        "Mii Swordfighter",
        "Mii Gunner",
        "Palutena",
        "Pac-Man",
        "Robin",
        "Shulk",
        "Bowser Jr.",
        "Duck Hunt",
        "Cloud",
        "Corrin",
        "Bayonetta",
        "Inkling",
        "Ridley",
        "Simon",
        "Richter",
        "King K. Rool",
        "Isabelle",
        "Incineroar",
        "Piranha Plant",
        "Banjo & Kazooie",
        "Terry",
        "Min Min",
        "Steve",
        "Sephiroth",
        "Pyra",
        "Mythra",
        "Kazuya",
        "Sora"
    ],
    smallerAnimes: [
        "Erased",
        "Made in Abyss",
        "Psycho-Pass",
        "Assassination Classroom",
        "Akame ga Kill!",
        "Ghost in the Shell",
        "Saga of Tanya the Evil",
        "Yuri!!! on Ice",
        "Cells at Work!",
        "Golden Kamuy",
        "The Seven Deadly Sins",
        "Death Parade",
        "Black Lagoon",
        "Detective Conan",
        "Parasyte",
        "Your Lie in April",
        "Initial D",
        "Fruits Basket",
        "Oshi no Ko",
        "Idol",
        "Ai Hoshino",
        "Yoasobi",
        "Ruby Hoshino",
        "Aquamarine Hoshino",
        "Goblin Slayer",
        "Goblin",
        "Guilty Crown",
        "Samurai Champloo",
        "Dororo",
        "Hyakkimaru",
        "Tokyo Revengers",
        "Takemichi Hanagaki",
        "Durarara!!",
        "Celty Sturluson",
        "Kaguya-sama: Love Is War",
        "Chika Fujiwara",
        "Miyuki Shirogane",
        "Yu Ishigami",
        "Ai Hayasaka",
        "Kaguya Shinomiya",
        "Clannad",
        "Nagisa Furukawa",
        "High School DxD",
        "Rias Gremory",
        "Akeno Himejima",
        "Issei Hyoudou",
        "Elfen Lied",
        "The Rising of the Shield Hero",
        "Shield Hero",
        "Naofumi Iwatani",
        "Raphtalia",
        "Filo",
        "Shokugeki no Soma",
        "Food Wars!",
        "Soma Yukihira",
        "Erina Nakiri",
        "No Game No Life",
        "Koro-sensei",
        "Gurren Lagann",
        "Kamina",
        "Kuroko no Basket",
        "Kuroko",
        "Gintama",
        "Gintoki Sakata",
        "Cyberpunk: Edgerunners",
        "Lucyna Kushinada",
        "Haikyu!!",
        "Kei Tsukishima",
        "Toru Oikawa",
        "Tobio Kageyama",
        "Kenma Kozume",
        "Shoyo Hinata",
        "Yū Nishinoya",
        "Kôshi Sugawara",
        "Daichi Sawamura",
        "Ryûnosuke Tanaka",
        "Asahi Azumane",
        "Ranma",
        "Union Arena Card",
        "Yu-Gi-Oh",
        "Yu-Gi-Oh Card",
        "Duel Disk",
        "Joey Wheeler",
        "Yugi Muto",
        "Maximillion Pegasus",
        "Mai Valentine",
        "Seto Kaiba",
        "Yami  Yugi",
        "Code Geass",
        "Lelouch Vi Britannia",
        "Euphemia Li Britannia",
        "Schneizel El Britannia",
        "Nunnally",
        "Charles zi Britannia",
        "Rolo Lamperouge",
        "Shirley Fenette",
        "C.C.",
        "Kallen Stadtfeld",
        "Suzaku Kururugi",
        "Vinland Saga",
        "Thorfinn",
        "Askeladd",
        "Thorkell",
        "Tokyo Ghoul",
        "Ken Kaneki",
        "Soul Eater",
        "Death the Kid",
        "Maka Albarn",
        "Totoro",
        "Darling in the Franxx",
        "Zero Two",
        "Eyeshield 21",
        "Blue Lock",
        "Cowboy Bebop",
        "Spike Spiegel",
        "Death Note",
        "L",
        "Light Yagami",
        "Ryuk",
        "Misa Amane",
        "Madoka Magica",
        "Magic Girls",
        "Madoka Kaname",
        "Homura Akemi",
        "Full Metal Alchemist",
        "Winry Rockbell",
        "Edward Elric",
        "Gluttony",
        "Riza Hawkey",
        "Alex Louis Armstrong",
        "Olivier Mira Armstrong",
        "Edward",
        "Alphonse Elric",
        "Roy Mustang",
        "King Bradley",
        "Gundam",
        "Gundam Card",
        "MGEX Strike Freedom Gundam",
        "MG Sazabi Ver.Ka",
        "MG Gundam Barbatos (MG IBO Barbatos)",
        "RG Hi‑Nu Gundam",
        "PG Unleashed RX‑78‑2 Gundam",
        "MG RX‑78‑2 Gundam Ver. 3.0",
        "MG Unicorn Gundam (MG/Destory Mode)",
        "MG Nu Gundam Ver.Ka",
        "RG God Gundam",
        "MG Zaku II (various)",
        "MG Gundam Exia",
        "MG 00 Raiser",
        "MG Gundam Virtue",
        "HG Gundam Aerial",
        "HG Gundam Calibarn",
        "HG Gundam Lfrith",
        "RG Gundam Epyon",
        "HG Barbatos Lupus Rex",
        "MG Wing Gundam Zero Ver.Ka",
        "RG Wing Gundam Zero Custom",
        "Spirited Away",
        "Kaonashi",
        "My Dress-Up Darling",
        "Marin Kitagawa",
        "Dan Da Dan",
        "Berserk",
        "Guts",
        "JoJo's Bizarre Adventure",
        "Joseph Joestar",
        "Jotaro Kujo",
        "Dio Brando",
        "Overlord",
        "Ainz Ooal Gown",
        "Albedo",
        "Shalltear Bloodfallen",
        "The Promised Neverland",
        "Isekai",
        "Hellsing",
        "Alucard",
        "Black Clover",
        "Noelle Silva",
        "Asta",
        "Yami Sukehiro",
        "Yuno",
        "Steins;Gate",
        "Kurisu Makise",
        "Inuyasha",
        "Sailor Moon",
        "Sailor Mercury",
        "Sailor Venus",
        "Tuxedo Mask",
        "Sailor Neptune",
        "Sailor Pluto",
        "Sailor Mars",
        "Sailor Saturn",
        "Neptune",
        "Frieren",
        "Himmel",
        "Fern",
        "Sakamoto Days",
        "Fire Force",
        "Sword Art Online",
        "Kirito",
        "Kazuto Kirigaya",
        "Asuna",
        "Dr. Stone",
        "Senku Ishigami",
        "Taiju Oki",
        "That Time I Got Reincarnated as a Slime",
        "Rimuru Tempest",
        "Benimaru",
        "Milim",
        "One-Punch Man",
        "Genos",
        "Garou",
        "Mumen Rider",
        "Saitama",
        "King",
        "Chainsaw Man",
        "Denji",
        "Pochita",
        "Aki Hayakawa",
        "Makima",
        "Power",
        "Kill la Kill",
        "Ryuko Matoi",
        "Tennis",
        "Prince of Tennis",
        "Solo Leveling",
        "Beastars",
        "Trigun",
        "Trigun Stampede",
        "Vash the Stampede",
        "Kaiju No. 8",
        "Kafka Hibino",
        "Mob Psycho 100",
        "Shigeo Kageyama",
        "Arataka Reigen",
        "Ritsu Kageyama",
    ],
    wutheringWaves: [
        "Wuthering Waves",
        "Verina", "Jiyan", "Jinhsi", "Camellya", "Carlotta",
        "Brant", "Zani", "Phoebe", "Shorekeeper", "Xiangli Yao",
        "Yinlin", "Calcharo", "Encore", "Changli", "Sanhua",
        "Mortefi", "Roccia", "Cantarella", "Yangyang", "Rover (Havoc)",
        "Rover (Spectro)", "Rover (Aero)", "Verina (alt)", "Jianxin",
        "Danjin", "Baizhi", "Yuanwu", "Youhu", "Lumi", "Chixia", "Lingyang"
    ],
    zenlessZoneZero: [
        "Zenless Zone Zero",
        // S+ Tier (Elite agents excelling in their roles)
        "Miyabi",
        "Astra Yao",
        "Lighter",
        "Yanagi",
        "Caesar King",
        "Jane Doe",
        "Zhu Yuan",
        "Ellen",
        "Lycaon",
        "Qingyi",

        // S Tier (High-impact supports, sub‑DPS, and generalists)
        "Burnice",
        "Grace",
        "Nicole",
        "Lucy",
        "Rina",
        "Anby",
        "Soukaku",
        "Koleda",
        "Soldier 11",
        "Piper",
    ],
    videoGames: [
        "Runescape",
        "Silent Hill",
        "Grand Theft Auto",
        "Borderlands",
        "Animal Crossing",
        "The Sims",
        "The Oregon Trail",
        "BioShock",
        "Terraria",
        "Stardew Valley",
        "Hades",
        "Call of Duty",
        "Skyrim",
        "Danganronpa",
        "Monokuma",
        "Commander Shepard",
        "Ezio Auditore",
        "Assassin's Creed",
        "Aloy",
        "Undertale",
        "Sans",
        "Cuphead",
        "Pikmin",
        "Nintendo",
        "Capcom",
        "Sony",
        "Bandai Namco",
        "Five Nights At Freddy's",
        "Freddy Fazbear",
        "Guilty Gear",
        "Sol Badguy",
        "Tekken",
        "Jin Kazama",
        "Heihachi Mishima",
        "Jin",
        "Kazuya Mishima",
        "Monster Hunter",
        "Monster",
        "Hunter",
        "The Legend of Zelda",
        "Link",
        "Metroid",
        "Samus Aran",
        "Nathan Drake",
        "Fate/Stay Night",
        "Fate/Zero",
        "Saber",
        "Shovel Knight",
        "Hollow Knight",
        "Video Game",
        "Halo",
        "Master Chief",
        "Goddess of Victory: NIKKE",
        "Bomberman",
        "Baldur's Gate",
        "Fallout",
        "Tomb Raider",
        "Lara Croft",
        "Solid Snake",
        "Zero",
        "StarCraft",
        "Blizzard",
        "Diablo",
        "Warcraft",
        "Phoenix Wright",
        "Geno",
        "Frank West",
        "Castlevania",
        "Castle",
        "Simon Belmont",
        "Devil May Cry",
        "Dante",
        "Vergil",
        "Doom",
        "Doomguy",
        "Honkai: Star Rail",
        "Clair Obscur: Expedition 33",
        "Resident Evil",
        "Jill Valentine",
        "Ada Wong",
        "Albert Wesker",
        "Resident Evil 4",
        "Leon Scott Kennedy",
        "Chris Redfield",
        "HELLDIVERS",
        "Lethal Company",
        "The Last of Us",
        "Fatal Fury",
        "Iori Yagami",
        "NieR: Automata",
        "2B",
        "Parappa",
        "Elden Ring",
        "Godfrey",
        "God of War",
        "Kratos",
        "Minecraft",
        "Steve",
        "Jack Black",
        "Sonic",
        "Sonic the Hedgehog",
        "Shadow the Hedgehog",
        "Shadow",
        "Doctor Eggman",
        "Amy Rose",
        "Rouge the Bat",
        "Metal Sonic",
        "Knuckles",
        "Tails",
        "Terry Bogard",
        "SEGA",
        "Final Fantasy",
        "Final Fantasy 7",
        "Sephiroth",
        "Cloud Strife",
        "Buster Sword",
        "Yuna",
        "Chocobo",
        "Aerith Gainsborough",
        "Vivi Ornitier",
        "Zidane Tribal",
        "Emet‑Selch",
        "Tidus",
        "Lightning",
        "Tifa Lockhart",
        "Zack Fair",
        "Sephiroth",
        "Haurchefant Greystone",
        "Noctis Lucis Caelum",
        "Squall Leonhart",
        "Auron",
        "Gilgamesh",
        "Terra Branford",
        "Kain Highwind",
        "Celes Chere",
        "Locke Cole",
        "Among Us",
    ],
    persona : [
        "Persona",
        "Persona 3",
        "Persona 4",
        "Persona 5",
        "Phantom Thieves of Hearts",
        "Joker",
        "Makoto Yuki",
        "Kotone Shiomi",
        "Yukari Takeba",
        "Junpei Iori",
        "Mitsuru Kirijo",
        "Akihiko Sanada",
        "Fuuka Yamagishi",
        "Aigis",
        "Ken Amada",
        "Koromaru",
        "Shinjiro Aragaki",
        "Elizabeth",
        "Theodore",
        "Margaret",
        "Ryoji Mochizuki",
        "Takaya Sakaki",
        "Jin Shirato",
        "Chidori Yoshino",
        "Ikutsuki",
        "Yu Narukami",
        "Yosuke Hanamura",
        "Chie Satonaka",
        "Yukiko Amagi",
        "Kanji Tatsumi",
        "Rise Kujikawa",
        "Naoto Shirogane",
        "Teddie (Kuma)",
        "Tohru Adachi",
        "Margaret",
        "Marie",
        "Dojima Ryotaro",
        "Nanako Dojima",
        "Mitsuo Kubo",
        "Namatame Taro",
        "Ai Ebihara",
        "Yumi Ozawa",
        "Ayane Matsunaga",
        "Sayoko Uehara",
        "Hisano Kuroda",
        "Eri Minami",
        "Ren Amamiya",
        "Ryuji Sakamoto",
        "Ann Takamaki",
        "Morgana",
        "Yusuke Kitagawa",
        "Makoto Niijima",
        "Futaba Sakura",
        "Haru Okumura",
        "Goro Akechi",
        "Kasumi Yoshizawa",
        "Takuto Maruki",
        "Sae Niijima",
        "Sojiro Sakura",
        "Igor",
        "Caroline",
        "Justine",
        "Lavenza",
        "Munehisa Iwai",
        "Tae Takemi",
        "Sadayo Kawakami",
        "Chihaya Mifune",
        "Shinya Oda",
        "Ichiko Ohya",
        "Hifumi Togo",
        "Toranosuke Yoshida"
    ],
    marvel : [
        "Marvel",
        "Avengers",
        "Guardians of the Galaxy",
        "Marvel Rivals",
        "Cloak & Dagger",
        "Jeff the Land Shark",
        "Squirrel",
        "Squirrel Girl",
        "Fantastic Four",
        "Mister Fantastic",
        "Invisible Woman",
        "Emma Frost",
        "Peni Parker",
        "The Thing",
        "Luna Snow",
        "Hulk",
        "Magik",
        "Fantastic Four",
        "X-Men",
        "Wolverine",
        "Captain America",
        "Thor",
        "Iron Man",
        "Doctor Strange",
        "Black Panther",
        "Night Crawler",
        "Silver Surfer",
        "Deadpool",
        "Comic",
        "Comic Book",
        "Psylocke",
        "Miles Morales",
        "Venom",
        "Carnage",
        "Thanos",
        "Loki",
        "Spider-Man",
        "Black Widow",
        "Hawkeye",
        "Scarlet Witch",
        "Vision",
        "Ant-Man",
        "Wasp",
        "Captain Marvel",
        "Falcon",
        "Winter Soldier",
        "War Machine",
        "Star-Lord",
        "Gamora",
        "Drax",
        "Rocket Raccoon",
        "Groot",
        "Nebula",
        "Mantis",
        "Yondu",
        "Nick Fury",
        "Shang-Chi",
        "Moon Knight",
        "She-Hulk",
        "Daredevil",
        "Jessica Jones",
        "Luke Cage",
        "Iron Fist",
        "The Punisher",
        "Elektra",
        "Blade",
        "Ghost Rider",
        "Wolverine",
        "Professor X",
        "Magneto",
        "Cyclops",
        "Jean Grey",
        "Storm",
        "Beast",
        "Rogue",
        "Nightcrawler",
        "Colossus",
        "Mystique",
        "Deadpool",
        "Cable",
        "Domino",
        "Silver Surfer",
        "Galactus",
        "Thanos",
        "Red Skull",
        "Ultron",
        "Kang the Conqueror",
        "Green Goblin",
        "Venom",
        "Carnage",
        "Sandman",
        "Doctor Octopus",
        "Vulture",
        "Electro",
        "Mysterio",
        "Rhino",
        "Kingpin",
        "Bullseye",
        "Taskmaster",
        "Abomination",
        "Hela",
        "Gorr the God Butcher",
        "Uatu the Watcher",
        "The Living Tribunal",
        "Eternity",
        "Infinity",
        "The Beyonder",
        "Knull",
        "Sentry",
        "Nova",
        "Ironheart",
        "Miles Morales",
        "Spider-Gwen",
        "Spider-Woman",
        "X-23",
        "Agent Coulson",
        "Mockingbird",
        "Howard the Duck",
        "MODOK",
        "Arnim Zola",
        "Mephisto",
        "Namor",
    ],
    dc : [
        "DC",
        "Justice League",
        "Batman",
        "Barry Allen",
        "Catwoman",
        "Darkseid",
        "Poison Ivy",
        "Superman",
        "Wonder Woman",
        "Harley Quinn",
        "Robin",
        "Flash",
        "Teen Titans",
        "Starfire",
        "Raven",
        "Cyborg",
         // Heroes
        "The Flash",
        "Green Lantern",
        "Aquaman",
        "Martian Manhunter",
        "Green Arrow",
        "Black Canary",
        "Hawkman",
        "Hawkgirl",
        "Zatanna",
        "John Constantine",
        "Shazam",
        "Supergirl",
        "Batgirl",
        "Nightwing",
        "Red Hood",
        "Beast Boy",
        "Blue Beetle",
        "The Atom",
        "Vixen",
        "Booster Gold",
        "Plastic Man",
        "Batwoman",
        "Steel",
        "The Question",
        "Swamp Thing",
        "Firestorm",
        "Doctor Fate",
        "Doctor Light",
        "Orion",
        "Adam Warlock",
        "Mr. Miracle",
        "Big Barda",
        "Static",
        "Icon",
        "Rocket",
        "Katana",
        // Villains
        "The Joker",
        "Lex Luthor",
        "Darkseid",
        "Deathstroke",
        "Bane",
        "Ra's al Ghul",
        "Talia al Ghul",
        "Penguin",
        "Riddler",
        "Two-Face",
        "Scarecrow",
        "Poison Ivy",
        "Black Manta",
        "Sinestro",
        "Reverse-Flash (Eobard Thawne)",
        "Zoom (Hunter Zolomon)",
        "Captain Cold",
        "Gorilla Grodd",
        "Brainiac",
        "Doomsday",
        "Trigon",
        "Amanda Waller",
        "General Zod",
        "Cheetah",
        "Maxwell Lord",
        "Clayface",
        "Hush",
        "Solomon Grundy",
        "Lobo",
        "Killer Croc",
        "Deadshot",
        "Enchantress",
        "Killer Frost",
        "Black Adam",
        "Parallax",
        "Mongul",
        "The Batman Who Laughs",
        "Vandal Savage",
        "Prometheus",
        "Toyman"
    ],
    starWars : [
        "Star Wars",
        "Star Wars: The Clone Wars",
        "Wookiee",
        "Mandalorian",
        // Original Trilogy
        "Luke Skywalker",
        "Princess Leia Organa",
        "Stormtrooper",
        "Han Solo",
        "Chewbacca",
        "Darth Vader",
        "Obi-Wan Kenobi",
        "C-3PO",
        "R2-D2",
        "Yoda",
        "Lando Calrissian",
        "Boba Fett",
        "Emperor Palpatine",

        // Prequel Trilogy
        "Anakin Skywalker",
        "Padmé Amidala",
        "Qui-Gon Jinn",
        "Mace Windu",
        "Count Dooku",
        "Darth Maul",
        "Jar Jar Binks",
        "Shmi Skywalker",
        "Jango Fett",
        "Bail Organa",
        "Kit Fisto",
        "Plo Koon",
        "Shaak Ti",
        "Ki-Adi-Mundi",
        "Aayla Secura",

        // Sequel Trilogy
        "Rey",
        "Finn",
        "Poe Dameron",
        "Kylo Ren",
        "General Hux",
        "Captain Phasma",
        "Maz Kanata",
        "Supreme Leader Snoke",
        "BB-8",
        "Zorii Bliss",
        "Rose Tico",

        // Rogue One / Solo
        "Jyn Erso",
        "Cassian Andor",
        "K-2SO",
        "Saw Gerrera",
        "Galen Erso",
        "Orson Krennic",
        "Chirrut Îmwe",
        "Baze Malbus",
        "Enfys Nest",
        "Qi'ra",
        "Tobias Beckett",
        "Dryden Vos",
        "L3-37",

        // TV Series (Clone Wars, Rebels, Mandalorian, Ahsoka)
        "Ahsoka Tano",
        "Captain Rex",
        "Bo-Katan Kryze",
        "Pre Vizsla",
        "Cad Bane",
        "Asajj Ventress",
        "Ezra Bridger",
        "Kanan Jarrus",
        "Sabine Wren",
        "Hera Syndulla",
        "Garazeb Orrelios",
        "Grand Admiral Thrawn",
        "The Mandalorian",
        "Din Djarin",
        "Grogu",
        "Baby Yoda",
        "Moff Gideon",
        "Fennec Shand",
        "Cara Dune",
        "Cobb Vanth",
        "Baylan Skoll",
        "Shin Hati",
        "Morgan Elsbeth",
        "The Armorer",
        "Paz Vizsla",

        // Legends / Expanded Universe
        "Mara Jade",
        "Jacen Solo",
        "Jaina Solo",
        "Darth Revan",
        "Darth Malak",
        "Darth Nihilus",
        "Darth Bane",
        "HK-47",
        "Bastila Shan",
        "Cade Skywalker",
        "Exar Kun",

        // Miscellaneous
        "Wicket W. Warrick",
        "Nien Nunb",
        "Greedo",
        "Watto",
        "Sebulba",
        "Bib Fortuna",
        "Bossk",
        "IG-88",
        "4-LOM",
        "Zam Wesell",
        "Mon Mothma",
        "General Grievous",
        "Nute Gunray",
        "Poggle the Lesser",
        "Max Rebo"
    ],
    genshinImpact : [
        "Genshin Impact",
        "Kaedehara Kazuha",
        "Alhaitham",
        "Furina",
        "Navia",
        "Xilonen",
        "Hu Tao",
        "Clorinde",
        "Traveler (Aether/Lumine)",
        /* Mondstadt */
        "Amber","Kaeya","Lisa","Barbara","Razor","Klee","Venti","Jean","Sucrose","Diluc","Rosaria","Mona","Albedo","Xiangling","Diona","Bennett",
        /* Liyue */
        "Ningguang","Tartaglia", "Childe", "Xiao","Xingqiu","Zhongli","Qiqi","Ganyu","Keqing","Hu Tao","Chongyun","Xinyan","Yun Jin","Shenhe","Yelan","Baizhu","Mika","Dori","Candace",
        /* Inazuma */
        "Beidou","Kazuha","Thoma","Ayaka","Yae Miko","Yoimiya","Kujou Sara","Raiden Shogun","Gorou","Kuki Shinobu","Sayu","Arataki Itto","Kamisato Ayato","Shikanoin Heizou",
        /* Sumeru */
        "Tighnari","Nilou","Nahida","Cyno","Alhaitham","Faruzan","Wanderer","Yaoyao","Lyney","Yaoyao","Freminet","Neuvillette","Wriothesley","Layla","Kirara","Collei","Kaveh",
        /* Fontaine / Newer regions */
        "Mualani","Kachina","Kinich","Xilonen","Chasca","Ororon","Citlali","Mavuika","Lan Yan","Skirk","Dahlia","Ineffa","Arlecchino",
        "Xianyun",
        "Dehya",
        "Mika",
        "Baizhu",
        "Kaveh",
        "Sethos",
        "Ifa",
        "Escoffier",
        "Charlotte",
        "Chevreuse",
        "Emilie",
        "Yelan",
        "Layla",
        "Lyney",
        "Faruzan",
        "Yun Jin",
        "Yae Miko",
        "Yoimiya",
        "Kujou Sara",
        "Raiden Shogun",
        "Sayu",
        "Kuki Shinobu",
        "Arataki Itto",
        "Collei",
        "Wanderer",
        "Yaoyao",
        "Neuvillette",
        "Wriothesley",
        "Freminet",
        "Mavalika? No Mavuika",
        "Lan Yan",
        "Citlali",
        "Ororon",
        "Chasca",
        "Kachina",
        "Kinich",
        "Mualani",
        "Dehya",
        "Mika",
        "Baizhu",
        "Kaveh",
        "Sethos"
    ],
    pokemon : [
        "Pokemon",
        "Pokedex",
        "Gyarados",
        "Brock",
        "Misty",
        "Gym Leader",
        "Rayquaza",
        "Dragonite",
        "Mewtwo",
        "Poke Ball",
        "Great Ball",
        "Ultra Ball",
        "Master Ball",
        "Ash Ketchum",
        "Team Rocket",
        "Jirachi", "Darkrai", 
        "Diancie", "Hoopa", "Keldeo", "Victini", "Manaphy",
        "Reshiram", "Kyogre", "Kyurem", "Magnemite", "Shaymin",
        "Yveltal", "Giratina", "Lugia", "Groudon",
        "Dedenne", "Archeops", "Zekrom", "Suicune", 
        "Ho‑Oh", "Xerneas", "Celebi", "Piplup",
        "Regigigas", "Azelf",
        "Landorus", "Glaceon", "Latias","Deoxys",
        "Oshawott", "Articuno", "Absol", "Latios",
        "Ditto", "Fennekin", "Hydreigon",
        "Zapdos", "Salamence", "Flygon",
        "Moltres", "Goomy",
        "Raichu", "Metagross", "Froakie", "Cresselia", "Blastoise",
        "Emolga", "Arbok", "Milotic", "Lapras",
        "Swampert", "Beautifly", "Mawile", "Noivern",
        "Luxray", "Ampharos", "Archen", "Armaldo",
        "Magikarp", "Torchic", "Thundurus", "Flareon",
        "Porygon", "Chespin", "Raikou", "Machamp",
        "Detective Pikachu",
        "Charizard",
        "Eevee",
        "Greninja",
        "Gengar",
        "Mewtwo",
        "Mew",
        "Snorlax",
        "Bulbasaur",
        "Squirtle",
        "Psyduck",
        "Gardevoir",
        "Arcanine",
        "Umbreon",
        "Sylveon",
        "Vaporeon",
        "Leafeon",
        "Espeon",
        "Blaziken",
        "Infernape",
        "Togepi",
        "Scizor",
        "Zoroark",
        "Tyranitar",
        "Rayquaza",
        "Dialga",
        "Palkia",
        "Garchomp",
        "Chandelure",
        "Sceptile",
        "Mudkip",
        "Cinderace",
        "Tinkaton",
        "Fuecoco",
        "Sprigatito",
        "Quaxly",
        "Iron Valiant",
        "Mimikyu",
        "Corviknight",
        "Dragapult",
        "Rillaboom",
        "Decidueye",
        "Professor Oak",
        "Professor Kukui",
        "Leon",
        "Cynthia",
        "Giovanni",
        "Meowth",
        "Ivysaur", "Venusaur", "Charmeleon", "Charizard (Mega X)", "Charizard (Mega Y)",
        "Wartortle", "Blastoise (Mega)", "Caterpie", "Metapod", "Butterfree",
        "Weedle", "Kakuna", "Beedrill (Mega)", "Pidgey", "Pidgeotto",
        "Pidgeot (Mega)", "Rattata", "Raticate", "Fearow", "Ekans",
        "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen",
        "Nidoran♂", "Nidorino", "Nidoking", "Clefairy", "Clefable",
        "Vulpix", "Ninetales", "Jigglypuff", "Wigglytuff", "Zubat",
        "Golbat", "Oddish", "Gloom", "Vileplume", "Paras",
        "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio",
        "Meowth (Alolan)", "Psyduck", "Golduck", "Mankey", "Primeape",
        "Growlithe", "Arcanine", "Poliwag", "Poliwhirl", "Poliwrath",
        "Abra", "Kadabra", "Alakazam (Mega)", "Machop", "Machoke",
        "Machamp", "Bellsprout", "Weepinbell", "Victreebel", "Tentacool",
        "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta",
        "Rapidash", "Slowpoke", "Slowbro (Mega)", "Magnemite", "Magneton",
        "Farfetch'd", "Doduo", "Dodrio", "Seel", "Dewgong",
        "Grimer", "Muk", "Shellder", "Cloyster", "Gastly",
        "Haunter", "Gengar (Mega)", "Onix", "Drowzee", "Hypno",
        "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute",
        "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan",
        "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon",
        "Chansey", "Tangela", "Kangaskhan (Mega)", "Horsea", "Seadra",
        "Goldeen", "Seaking", "Staryu", "Starmie", "Mr. Mime",
        "Scyther", "Jynx", "Electabuzz", "Magmar", "Pinsir (Mega)",
        "Tauros", "Magikarp", "Gyarados (Mega)", "Lapras", "Ditto", "Jolteon",
        "Porygon2", "Omanyte", "Omastar", "Kabuto", "Kabutops"
    ],
    streetFighter : [
        "Street Fighter",
        "Sakura Kasugano",
        "Ryu",
        "Ken Masters",
        "Akuma",
        "Chun-Li",
        "Guile",
        "Zangief",
        "Cammy",
        "Blanka",
        "Juri"
    ],
    shows : [
        "Dora Márquez",
        "Dora",
        "Dora the Explorer",
        "Alvin Seville",
        "Theodore Seville",
        "Lord of the Rings",
        "Gollum",
          // Hobbits & Ring‑bearers
        "Frodo Baggins",
        "Samwise Gamgee",
        "Meriadoc 'Merry' Brandybuck",
        "Peregrin 'Pippin' Took",
        "Bilbo Baggins",
        "Sméagol",
        "Frodo Baggins",
        "Indiana Jones",
        "Mickey Mouse",
          // Fellowship & Rangers
        "Aragorn",
        "Gandalf the Grey / White",
        "Legolas",
        "Gimli",
        "Boromir",
        "Freddy Krueger",
        "Michael Myers",
        "Ghostface",
        // Elves & Rulers
        "Arwen Undómiel",
        "Elrond",
        "Galadriel",
        "Celeborn",

        // Rohan
        "Théoden",
        "Éomer",
        "Éowyn",
        "Gríma Wormtongue" ,

        // Gondor & Others
        "Faramir",
        "Denethor II",
        "Treebeard",
        "Radagast the Brown",
        "Círdan the Shipwright",
        "Beregond",
        "Bergil",

        // Wizards & Maiar
        "Saruman the White",
        "Sauron",
        "The Witch‑king of Angmar (Nazgûl)",
        "Mary Poppins",
        "The Terminator",
        "Brief Case",
        "Treasure Chest",
        "Donald Duck",
        "Minnie Mouse",
        "Goofy",
        "Stitch",
        "My Little Pony",
        "Pinkie Pie",
        "Applejack",
        "Twilight Sparkle",
        "Fluttershy",
        "Rainbow Dash",
        "Invader Zim",
        "South Park",
        "Family Guy",
        "Breaking Bad",
        "Looney Tunes",
        "Sherlock",
        "Game of Thrones",
        "The Simpsons",
        "The Office",
        "Gravity Falls",
        "The Amazing World of Gumball",
        "Dexter’s Laboratory",
        "DuckTales",
        "Courage the Cowardly Dog",
        "Johnny Bravo",
        "Phineas and Ferb",
        "Steven Universe",
        "Ed, Edd n Eddy",
        "Ben 10",
        "Thundercats",
        "Gargoyles",
        "Fairly OddParents",
        "The Flintstones",
        "The Jetsons",
        "Hey Arnold!",
        "Inspector Gadget",
        "Regular Show",
        "Tom & Jerry",
        "Star Trek",
        "The Walking Dead",
        "Stranger Things",
        "How to Train Your Dragon",
        "Hiccup Horrendous Haddock III",
        "Astrid Hofferson",
        "Toothless",
        "The Powerpuff Girls",
        "RWBY",
        "King of the Hill",
        "Hank Hill",
        "Digimon",
        "Agumon",
        "Patamon",
        "Gabumon",
        "Tai Kamiya",
        "Disney",
        "The Lion King",
        "Cinderella",
        "Ursula",
        "Simba",
        "Moana",
        "Lightning McQueen",
        "Captain Hook",
        "Captain Jack Sparrow",
        "Cruella de Vil",
        "Tinker Bell",
        "Genie",
        "Winnie-the-Pooh",
        "The Little Mermaid",
        "Aladdin",
        "Mulan",
        "Toy Story",
        "Buzz Lightyear",
        "Woody",
        "Peter Pan",
        "Jack Skellington",
        "Maleficent",
        "Elsa",
        "Snow White",
        "Harry Potter",
        "The Witcher",
        "Geralt of Rivia",
        "Henry Cavill",
        "Yennefer",
          // Classic Cartoons
        "Bugs Bunny",
        "Daffy Duck",
        "Tweety Bird",
        "Porky Pig",
        "Scooby-Doo",
        "Shaggy Rogers",
        "Fred Flintstone",
        "Barney Rubble",
        "George Jetson",
        "Astro",
        "Yogi Bear",
        "Boo Boo",
        "Felix the Cat",
        "Squidward Tentacles",
        "Sandy Cheeks",
        "Chowder",
        "The Grim Adventures of Billy & Mandy",
        "Jimmy Neutron",
        "Carl Wheezer",
        "Sheen Estevez",
        "Timmy Turner",
        "Cosmo",
        "Wanda",
        "Danny Phantom",
        "Teenage Mutant Ninja Turtles",
        "Power Ranger",
        "Spongebob",
        "SpongeBob SquarePants",
        "Patrick",
        "Patrick Star",
        "Sandy",
        "Gary",
        "Plankton",
        "Mr. Krabs",
        "Invincible",
        "Hazbin Hotel",
        "Beetlejuice",
        "Dune",
        "Futurama",
        "Squid Games",
        "Adventure time",
        "Finn the Human",
        "Princess Bubblegum",
        "Earl of Lemongrab",
        "Flame Princess",
        "Jake the Dog",
        "Bunny girl",
        "Queen",
        "Rick and Morty",
        "Pickle Rick",
        "Rick",
        "Morty",
        "Morty Smith",
        "Rick Sanchez",
        "Birdperson",
        "Jerry Smith",
        "Mr. Poopybutthole",
        "Mr. Meeseeks",
        "Evil Morty",
    ],
    others : [
        "Tragic Backstory",
        "Best Anime Opening",
        "Worst Anime Opening",
        "Artist",
        "Mime",
        "Painter",
        "Paint",
        "Musician",
        "Campfire",
        "Gatorade",
        "Bounty Hunter",
        "The Terminator",
        "Red Hair",
        "Blue Hair",
        "Green Hair",
        "Yellow Hair",
        "White Hair",
        "Purple Hair",
        "Black Hair",
        "Brown Hair",
        "Long Hair",
        "Short Hair",
        "Pink Hair",
        "Father",
        "Mother",
        "Teacher",
        "Student",
        "Shooter",
        "Melee",
        "Skateboard",
        "Brain rot",
        "TikTok",
        "Music",
        "America",
        "Bruno Mars",
        "Taylor Swift",
        "Drake",
        "Big Sword",
        "Small Sword",
        "Katana",
        "Arrow",
        "Shuriken",
        "Crossbow",
        "Slingshot",
        "Jetpack",
        "Big Weapon",
        "Legos",
        "Ramen",
        "Rice ball",
        "Onigiri",
        "Mummy",
        "Sword",
        "Bow",
        "Staff",
        "Axe",
        "Hammer",
        "Dagger",
        "Mace",
        "Wand",
        "Shield",
        "Gun",
        "Glasses",
        "Mascot",
        "Mask",
        "Aura",
        "NPC",
        "God",
        "Scam",
        "Scammer",
        "Food Truck",
        "Dr. Pepper",
        "Coke",
        "Coca-Cola",
        "Sprite",
        "Fanta",
        "Uncle Sam",
        "Convention food",
        "Pokemon Card",
        "Booster Pack",
        "Starter Deck",
        "Magic: The Gathering",
        "One Piece Card",
        "Dragon Ball Card",
        "Mystery Box",
        "Mousepad",
        "Keyboard",
        "Laptop",
        "Anime Clothes",
        "Overprice Food",
        "Metrocon Theme",
        "Weapon",
        "Sticker",
        "Labubu",
        "Artwork",
        "Art",
        "Manga",
        "Selfie",
        "Figurine",
        "Egg",
        "Plushie",
        "Keychain",
        "Poster",
        "Wanted Poster",
        "Funko Pop",
        "Hat",
        "Cowboy",
        "Cowboy Hat",
        "Pin",
        "Dice",
        "Mouse",
        "Food",
        "Impossible",
        "Anime Shirt",
        "Bunny ears",
        "Cat ears",
        "Cat girl",
        "Waifu",
        "Husbando",
        "Maid",
        "Furry",
        "Shinobi",
        "Ninja",
        "Elf",
        "Human",
        "Orc",
        "Dwarf",
        "Kimono",
        "Badass",
        "Samurai",
        "Bookmark",
        "Powerful",
        "Respected",
        "Brave",
        "Spirit",
        "Celestial",
        "Golem",
        "Undead",
        "Troll",
        "Yeti",
        "Tattoo",
        "Fire",
        "Water",
        "Popular",
        "Warrior",
        "Rogue",
        "Archer",
        "Mage",
        "Priest",
        "Shaman",
        "Healer",
        "Tank",
        "Warlock",
        "Paladin",
        "Druid",
        "Pirate",
        "Alien",
        "Overpowered",
        "Underpowered",
        "Underdog",
        "Ugly",
        "Sexy",
        "Handsome",
        "18 +",
        "Weak",
        "Strong",
        "Coward",
        "Cute",
        "Robot",
        "Shirtless",
        "Yakuza",
        "Mafia",
        "Jesus",
        "Witch",
        "Under $1",
        "Over $1",
        "Under $2",
        "Over $2",
        "Under $3",
        "Over $3",
        "Under $4",
        "Over $4",
        "Under $5",
        "Over $5",
        "Under $6",
        "Over $6",
        "Under $7",
        "Over $7",
        "Under $8",
        "Over $8",
        "Under $9",
        "Over $9",
        "Over $10",
        "Under $10",
        "Over $15",
        "Under $15",
        "Over $20",
        "Under $20",
        "Over $25",
        "Under $25",
        "Over $30",
        "Under $30",
        "Over $35",
        "Under $35",
        "Over $40",
        "Under $40",
        "Over $45",
        "Under $45",
        "Over $50",
        "Under $50",
        "Under $60",
        "Over $60",
        "Over $70",
        "Under $70",
        "Over $80",
        "Under $80",
        "Over $90",
        "Under $90",
        "Over $100",
        "Under $100",
        "Speedster",
        "Super Hero",
        "Hero",
        "Villain",
        "Ring",
        "Jewelry",
        "Necklace",
        "Body Pillow",
        "Flag",
        "Banner",
        "Badge",
        "Backpack",
        "Bag",
        "Pouch",
        "Coin",
        "Rich",
        "Royalty",
        "Outcast",
        "Vigilante",
        "Headphones",
        "Headband",
        "Bracelet",
        "Phone Case",
        "Claw Machine",
        "Princess",
        "Rizz",
        "Prince",
        "Soldier",
        "Cape",
        "Gacha",
        "Board Games",
        "Dragon",
        "Hololive",
        "VTuber",
        "Live Streamer",
        "Streamer",
        "Content Creator",
        "Influencer",
        "Youtuber",
        "Twitch Streamer",
        "Photographer",
        "Camera",
        "Instagram",
        "Unique",
        "Gawr Gura",
        "Sports",
        "K-Pop",
        "KPop Demon Hunters",
        "New Jeans",
        "BTS",
        "Waldo",
        "Snoopy",
        "John Cena",
        "Randy Orton",
        "The Undertaker",
        "The Rock",
        "Hulk Hogan",
        "Stone Cold Steve Austin",
        "Zombie",
        "Spawn",
        "Shoujo",
        "Shonen",
        "White Knight",
        "Knight",
        "Mecha",
        "Boy's Love",
        "BL",
        "Hello Kitty",
        "Robin Hood",
        "Hatsune Miku",
        "Vocaloid",
        "DND",
        "Umamusume: Pretty Derby",
        "Kaden",
        "Aaron",
        "Lex",
        "Eldon",
        "Jacob",
        "Dawn",
        "Cosplayer",
    ],
};

// Helper to flatten all scavengerObjects arrays into one array
function getAllScavengerItems() {
    return Object.values(scavengerObjects).flat();
}

// Shuffle function
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

function fillBingoCard() {
    const items = getAllScavengerItems();
    shuffle(items);
    let itemIndex = 0;
    for (let i = 0; i < 25; i++) {
        if (i === 12) continue; // skip center
        const cell = document.getElementById('cell-' + i);
        if (cell && itemIndex < items.length) {
            cell.textContent = items[itemIndex++];
        }
    }
}

function getCurrentBingoCard() {
    const card = [];
    for (let i = 0; i < 25; i++) {
        if (i === 12) {
            card.push("FREE");
        } else {
            const cell = document.getElementById('cell-' + i);
            card.push(cell ? cell.textContent : "");
        }
    }
    return card;
}

function renderSavedCard(name, card) {
    const table = document.createElement('table');
    table.className = "saved-bingo-table";
    const tbody = document.createElement('tbody');
    for (let row = 0; row < 5; row++) {
        const tr = document.createElement('tr');
        for (let col = 0; col < 5; col++) {
            const idx = row * 5 + col;
            const td = document.createElement('td');
            td.textContent = card[idx];
            if (idx === 12) {
                td.className = "free-cell";
            }
            tr.appendChild(td);
        }
        tbody.appendChild(tr);
    }
    table.appendChild(tbody);

    const wrapper = document.createElement('div');
    wrapper.className = "saved-card-wrapper";

    // Title and delete button in a row
    const titleRow = document.createElement('div');
    titleRow.className = "saved-card-title-row";

    const title = document.createElement('div');
    title.className = "saved-card-title";
    title.textContent = name ? `Saved by: ${name}` : "Saved Card";

    // Add delete button
    const delBtn = document.createElement('button');
    delBtn.textContent = "Delete";
    delBtn.className = "saved-card-delete-btn";
    delBtn.addEventListener('click', function() {
        wrapper.remove();
    });

    titleRow.appendChild(title);
    titleRow.appendChild(delBtn);

    wrapper.appendChild(titleRow);
    wrapper.appendChild(table);

    document.getElementById('saved-cards').appendChild(wrapper);
}

// this saves the bingo card
document.addEventListener('DOMContentLoaded', function() {
    fillBingoCard();
    document.getElementById('reroll-bingo').addEventListener('click', fillBingoCard);

    document.getElementById('save-bingo').addEventListener('click', function() {
        const name = document.getElementById('player-name').value.trim();
        const card = getCurrentBingoCard();
        renderSavedCard(name, card);
    });
});

// When the prize text is clicked on, it reveals it
document.getElementById('prize-text').onclick = function() {
    this.style.background = 'linear-gradient(90deg, #43cea2, #185a9d)';
    this.innerText = 'First person to get BINGO wins $100 cash!';
};
