// Countdown
function updateCountdown() {
    const targetDate = new Date('2025-07-25T00:00:00');
    const now = new Date();
    const diff = targetDate - now;

    if (diff <= 0) {
        document.getElementById('timer').textContent = "Metrocon Day!";
        clearInterval(timerInterval);
        return;
    }

    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    const hours = Math.floor((diff / (1000 * 60 * 60)) % 24);
    const minutes = Math.floor((diff / (1000 * 60)) % 60);
    const seconds = Math.floor((diff / 1000) % 60);

    document.getElementById('timer').textContent =
        `${days}d ${hours}h ${minutes}m ${seconds}s`;
}

const timerInterval = setInterval(updateCountdown, 1000);
updateCountdown();

// --- BINGO LOGIC ---

const scavengerObjects = {
    leagueOfLegends: [
        "K/DA",
        "Teemo",
        "Lux",
        "Garen",
        "Lee Sin",
        "Annie",
        "Gragas",
        "Twisted Fate",
        "Vladimir",
        "Senna",
        "Lucian",
        "Xayah",
        "Sett",
        "Shen",
        "Akali",
        "Draven",
        "Darius",
        "Shaco",
        "Vayne",
        "Talon",
        "Singed",
        "Riven",
        "Master Yi",
        "Leona",
        "Soraka",
        "Braum",
        "Miss Fortune",
        "Xin Zhao",
        "Zed",
        "Ryze",
        "Ashe",
        "Tryndamere",
        "Zeri",
        "Ezreal",
        "Janna",
        "Rakan",
        "Kennen",
        "Ahri",
        "Yasuo",
        "Yone",
    ],
    arcane : [
        "Arcane",
        "Ekko",
        "Jinx",
        "Vi",
        "Caitlyn",
        "Viktor",
        "Jayce"
    ],
    valorant : [
        "Valorant",
        "Jett",
        "Brimstone",
        "Viper",
        "Killjoy",
        "Gekko",
        "Yoru",
        "Raze",
        "Clove",
        "Reyna",
        "Sage",
        "Phoenix",
        "Omen",
        "Neon",
        "Chamber",
        "Sova",
        "Cypher",
    ],
    demonSlayer : [
        "Demon Slayer",
        "Muzan Kibutsuji",
        "Shinobu Kochō",
        "Tanjiro Kamado",
        "Nezuko Kamado",
        "Giyu Tomioka",
        "Zenitsu Agatsuma",
        "Inosuke Hashibira",
        "Kyōjurō Rengoku",
        "Tengen Uzui",
        "Mitsuri Kanroji",
        "Akaza",
    ],
    jujutsuKaisen: [
        "Jujutsu Kaisen",
        "Toji Fushiguro",
        "Yuji Itadori",
        "Nobara Kugisaki",
        "Megumi Fushiguro",
        "Maki Zen'in",
        "Aoi Todo",
        "Mahito",
        "Suguru Geto",
        "Panda",
        "Kento Nanami",
        "Satoru Gojo",
        "Ryomen Sukuna",
    ],
    onePiece: [
        "One Piece",
        "Sanji",
        "Brook",
        "Buggy",
        "Bartolomeo",
        "Dracule Mihawk",
        "Edward Newgate",
        "Whitebeard",
        "Boa Hancock",
        "Shanks",
        "Monkey D. Luffy",
        "Straw Hat",
        "Straw Hat Pirates",
        "Nico Robin",
        "Franky",
        "Usopp",
        "Nami",
        "Portgas D. Ace",
        "Donquixote Doflamingo",
        "Trafalgar D. Water Law",
        "Tony Tony Chopper",
        "Roronoa Zoro",
    ],
    attackOnTitan: [
        "Attack on Titan",  
        "Founding Titan",
        "Armored Titan",
        "Armored",
        "Attack Titan",
        "Beast Titan",
        "Beast",
        "Cart Titan",
        "Cart",
        "Colossus Titan",
        "Colossus",
        "Female Titan",
        "Female",
        "Male",
        "Jaw Titan",
        "War Hammer Titan",
        "Eren Yeager",
        "Mikasa Ackerman",
        "Levi Ackerman",
        "Armin Arlert",
        "Erwin Smith",
        "Annie Leonhart",
        "Sasha Braus",
        "Titan",
    ],
    myHeroAcademia: [
        "My Hero Academia",
        "Keigo Takami",
        "Ochaco Uraraka",
        "Izuku Midoriya",
        "Katsuki Bakugo",
        "Shoto Todoroki",
        "Himiko Toga",
    ],
    spyXFamily: [
        "Spy x Family",
        "Loid Forger",
        "Yor Forger",
        "Anya Forger",
    ],
    neonGenesisEvangelion: [
        "Neon Genesis Evangelion",
        "Asuka Langley Soryu",
        "Rei Ayanami",
    ],
    yuYuHakusho: [
        "YuYu Hakusho",
        "Kazuma Kuwabara",
        "Yusuke Urameshi",
        "Hiei",
    ],
    theBoys: [
        "The Boys",
        "Homelander",
    ],
    fairyTail: [
        "Fairy Tail",
        "Natsu Dragneel",
        "Lucy Heartfilia",
        "Juvia Lockser",
    ],
    dragonBall: [
        "Dragon Ball",
        "Dragon Ball Z",
        "Dragon Ball Super",
        "Dragon Ball Daima",
        "Kid Goku",
        "Android",
        "Master Roshi",
        "Videl",
        "Broly",
        "Vegeta",
        "Ginyu Force",
        "Super Saiyan",
        "Bulma",
        "Great Saiyaman",
        "Cell",
        "Frieza",
        "Trunks",
        "Android 18",
        "Android 17",
        "Son Goku",
        "Son Gohan",
        "Son Goten",
        "Majin Buu",
        "Piccolo",
    ],
    mortalKombat: [
        "Mortal Kombat",
        "Scorpion",
    ],
    overwatch: [
        "Overwatch",
        "Junkrat",
        "Genji",
        "Doomfist",
        "D.Va",
        "Reaper",
        "Tracer",
        "Winston",
    ],
    hunterXHunter: [
        "Hunter x Hunter",
        "Killua Zoldyck",
        "Hisoka",
        "Gon Freecss",
        "Kurapika",
    ],
    bleach: [
        "Bleach",
        "Ichigo Kurosaki",
        "Rukia Kuchiki",
        "Kenpachi Zaraki",
        "Kisuke Urahara",
        "Renji Abarai",
        "Sousuke Aizen",
        "Grimmjow Jaegerjaquez",
        "Nel tu",
    ],
    konoSuba: [
        "KonoSuba",
        "Kazuma Sato",
        "Aqua",
        "Megumin",
    ],
    naruto: [
        "Naruto",
        "Naruto Uzumaki",
        "Sasuke Uchiha",
        "Sakura Haruno",
        "Kakashi Hatake",
        "Madara Uchiha",
        "Obito Uchiha",
        "Tobi",
        "Kaguya Ōtsutsuki",
        "Nagato",
        "Pain",
        "Kabuto Yakushi",
        "Orochimaru",
        "Zabuza Momochi",
        "Haku",
        "Hinata Hyuga",
        "Shikamaru Nara",
        "Rock Lee",
        "Neji Hyuga",
        "Choji Akimichi",
        "Ino Yamanaka",
        "Kiba Inuzuka",
        "Shino Aburame",
        "Tenten",
        "Might Guy",
        "Asuma Sarutobi",
        "Kurenai Yuhi",
        "Iruka Umino",
        "Yamato",
        "Sai",
        "Tsunade Senju",
        "Hiruzen Sarutobi",
        "Minato Namikaze",
        "Hashirama Senju",
        "Tobirama Senju",
        "Gaara",
        "Itachi Uchiha",
        "Killer Bee",
        "Kurama",
        "Nine-Tails",
        "Deidara",
        "Sasori",
        "Kisame Hoshigaki",
        "Hidan",
        "Kakuzu",
        "Konan",
        "Jiraiya",
        "Rin Nohara",
        "Danzo Shimura",
        "Sharingan",
        "Akatsuki",
    ],
    fireEmblem: [
        "Fire Emblem",
        "Marth",
        "Roy",
        "Lyn",
        "Lucina",
        "Tiki",
        "Ike",
        "Corrin",
        "Black Knight",
        "Claude von Riegan",
        "Edelgard von Hresvelg",
        "Dimitri Alexandre Blaiddyd",
        "Byleth",
        "Sothis",
        "Lysithea",
    ],
    warhammer: [
        "Warhammer",
        "Space Marines",
        "Chaos Knights",
        "Tyranids",
        "Thousand Sons",
    ],
    reZero: [
        "Re:Zero",
        "Emilia",
        "Rem",
        "Ram",
        "Subaru Natsuki",
    ],
    superMario: [
        "Super Mario",
        "Yoshi",
        "Luigi",
        "Wario",
        "Waluigi",
        "Bowser",
        "Princess Peach",
        "Peach",
        "Daisy",
        "Toad",
    ],
    avatarTheLastAirbender: [
        "Avatar: The Last Airbender",
        "Aang",
        "Zuko",
        "Katara",
        "Toph Beifong",
        "Azula",
        "Sokka",
        "Uncle Iroh",
        "Appa",
    ],
    superSmashBrosUltimate: [
        "Super Smash Bros. Ultimate",
        "Ness",
        "Falco Lombardi",
        "King Dedede",
        "Kirby",
        "Meta Knight",
        "Pac-Man",
        "Donkey Kong",
        "Diddy Kong",
    ],
    smallerAnimes: [
        "Cyberpunk: Edgerunners",
        "Lucyna Kushinada",
        "Haikyu!!",
        "Ranma",
        "Yu-Gi-Oh",
        "Yugi Muto",
        "Yami  Yugi",
        "Code Geass",
        "Lelouch Vi Britannia",
        "C.C.",
        "Kallen Stadtfeld",
        "Vinland Saga",
        "Tokyo Ghoul",
        "Soul Eater",
        "Death the Kid",
        "Maka Albarn",
        "Totoro",
        "Darling in the Franxx",
        "Zero Two",
        "Blue Lock",
        "Cowboy Bebop",
        "Spike Spiegel",
        "Death Note",
        "L",
        "Light Yagami",
        "Ryuk",
        "Misa Amane",
        "Madoka Magica",
        "Madoka Kaname",
        "Homura Akemi",
        "Full Metal Alchemist",
        "Edward ",
        "Gundam",
        "Gundam Card",
        "Spirited Away",
        "Kaonashi",
        "My Dress-Up Darling",
        "Marin Kitagawa",
        "Dan Da Dan",
        "Berserk",
        "Guts",
        "JoJo's Bizarre Adventure",
        "Joseph Joestar",
        "Jotaro Kujo",
        "Dio Brando",
        "Overlord",
        "Ainz Ooal Gown",
        "The Promised Neverland",
        "Black Clover",
        "Steins;Gate",
        "Inuyasha",
        "Sailor Moon",
        "Frieren",
        "Sakamoto Days",
        "Fire Force",
        "Sword Art Online",
        "Kazuto Kirigaya",
        "Dr. Stone",
        "That Time I Got Reincarnated as a Slime",
        "Rimuru Tempest",
        "Benimaru",
        "Milim",
        "One-Punch Man",
        "Genos",
        "Garou",
        "Mumen Rider",
        "Saitama",
        "King",
        "Chainsaw Man",
        "Denji",
        "Pochita",
        "Aki Hayakawa",
        "Makima",
        "Power",
        "Kill la Kill",
        "Ryuko Matoi",
        "Prince of Tennis",
        "Solo Leveling",
        "Beastars",
        "Trigun Stampede",
        "Vash the Stampede",
        "Kaiju No. 8",
        "Kafka Hibino",
        "Mob Psycho 100",
    ],
    videoGames: [
        "Undertale",
        "Sans",
        "Cuphead",
        "Pikmin",
        "Nintendo",
        "Sony",
        "Five Nights At Freddy's",
        "Freddy Fazbear",
        "Guilty Gear",
        "Sol Badguy",
        "Tekken",
        "Jin Kazama",
        "Heihachi Mishima",
        "Jin",
        "Kazuya Mishima",
        "Monster Hunter",
        "The Legend of Zelda",
        "Link",
        "Metroid",
        "Samus Aran",
        "Nathan Drake",
        "Fate/Stay Night",
        "Saber",
        "Shovel Knight",
        "Hollow Knight",
        "Video Game",
        "Halo",
        "Master Chief",
        "Goddess of Victory: NIKKE",
        "Bomberman",
        "Baldur's Gate",
        "Fallout",
        "Lara Croft",
        "Solid Snake",
        "Mega Man",
        "Zero",
        "StarCraft",
        "Blizzard",
        "Diablo",
        "Phoenix Wright",
        "Geno",
        "Frank West",
        "Castlevania",
        "Simon Belmont",
        "Devil May Cry",
        "Dante",
        "Vergil",
        "Doom",
        "Doomguy",
        "Honkai: Star Rail",
        "Zenless Zone Zero",
        "Clair Obscur: Expedition 33",
        "Resident Evil",
        "Jill Valentine",
        "Ada Wong",
        "Albert Wesker",
        "Resident Evil 4",
        "Leon Scott Kennedy",
        "Chris Redfield",
        "HELLDIVERS",
        "Lethal Company",
        "The Last of Us",
        "Fatal Fury",
        "Iori Yagami",
        "NieR: Automata",
        "Parappa",
        "Elden Ring",
        "Godfrey",
        "God of War",
        "Kratos",
        "Minecraft",
        "Steve",
        "Jack Black",
        "Sonic",
        "Sonic the Hedgehog",
        "Knuckles",
        "Tails",
        "Terry Bogard",
        "SEGA",
        "Final Fantasy",
        "Final Fantasy 7",
        "Sephiroth",
        "Cloud Strife",
        "Buster Sword",
        "Aerith Gainsborough",
        "Tifa Lockhart",
        "Among Us",
    ],
    persona : [
        "Persona",
        "Persona 3",
        "Persona 4",
        "Persona 5",
        "Phantom Thieves of Hearts",
        "Joker",
        "Morgana",
        "Futaba Sakura",
    ],
    marvel : [
        "Marvel",
        "Marvel Rivals",
        "Luna Snow",
        "Hulk",
        "Magik",
        "Fantastic Four",
        "X-Men",
        "Wolverine",
        "Captain America",
        "Thor",
        "Iron Man",
        "Doctor Strange",
        "Black Panther",
        "Night Crawler",
        "Silver Surfer",
        "Deadpool",
        "Comic",
        "psylocke",
        "Spider-Man",
        "Miles Morales",
        "Venom",
        "Carnage",
        "Thanos",
        "Loki",
    ],
    dc : [
        "DC",
        "Batman",
        "Barry Allen",
        "Catwoman",
        "Darkseid",
        "Poison Ivy",
        "Superman",
        "Wonder Woman",
        "Harley Quinn",
        "Riddler",
        "Bane",
        "Robin",
        "Flash",
        "Teen Titans",
        "Starfire",
        "Raven",
        "Cyborg",
        "Beast boy",
    ],
    starWars : [
        "Star Wars",
        "Mandalorian",
        "Boba Fett",
        "Darth Vader",
        "Luke Skywalker",

    ],
    genshinImpact : [
        "Genshin Impact",
        "Klee",
        "Venti",
        "Diluc",
        "Neuvillette",
        "Zhongli",
        "Wanderer",
        "Kinich",
        "Kaedehara Kazuha",
        "Wriothesley",
        "Xiao",
        "Alhaitham",
        "Ororon",
        "Furina",
        "Arlecchino",
        "Raiden Shogun",
        "Nahida",
        "Navia",
        "Xilonen",
        "Hu Tao",
        "Mualani",
        "Clorinde",
        "Chasca",
    ],
    pokemon : [
        "Pokemon",
        "Brock",
        "Misty",
        "Gym Leader",
        "Rayquaza",
        "Dragonite",
        "Mewtwo",
        "Pokeball",
        "Ash Ketchum",
        "Team Rocket",
        "Pikachu",
        "Snorlax",
        "Eevee",
        "Vaporeon",
    ],
    streetFighter : [
        "Street Fighter",
        "Sakura Kasugano",
        "Ryu",
        "Ken Masters",
        "Akuma",
        "Chun-Li",
        "Guile",
        "Zangief",
        "Cammy",
        "Blanka",
        "Juri"
    ],
    shows : [
        "Teenage Mutant Ninja Turtles",
        "Power Ranger",
        "Spongebob",
        "SpongeBob SquarePants",
        "Patrick",
        "Patrick Star",
        "Squidward",
        "Sandy",
        "Gary",
        "Plankton",
        "Mr. Krabs",
        "Invincible",
        "Hazbin Hotel",
        "Beetlejuice",
        "Dune",
        "Futurama",
        "Squid Games",
        "Adventure time",
        "Bunny girl",
        "Queen",
        "Rick and Morty",
        "Pickle Rick",
        "Rick",
        "Morty",
    ],
    random : [
        "Music",
        "America",
        "Bruno Mars",
        "Taylor Swift",
        "Drake",
        "Big Sword",
        "Small Sword",
        "Katana",
        "Arrow",
        "Shuriken",
        "Crossbow",
        "Slingshot",
        "Jetpack",
        "Big Weapon",
        "Legos",
        "Sword",
        "Bow",
        "Staff",
        "Axe",
        "Hammer",
        "Dagger",
        "Mace",
        "Wand",
        "Shield",
        "Gun",
        "Glasses",
        "Mascot",
        "Mask",
        "Aura",
        "NPC",
        "God",
        "Food Truck",
        "Convention food",
        "Pokemon Card",
        "Magic: The Gathering",
        "One Piece Card",
        "Dragon Ball Card",
        "Mystery Box",
        "Mousepad",
        "Anime Clothes",
        "Overprice Food",
        "Metrocon Theme",
        "Weapon",
        "Sticker",
        "Labubu",
        "Artwork",
        "Manga",
        "Selfie",
        "Figurine",
        "Plushie",
        "Keychain",
        "Poster",
        "Funko Pop",
        "Hat",
        "Pin",
        "Dice",
        "Food",
        "Impossible",
        "Anime Shirt",
        "Bunny ears",
        "Cat ears",
        "Waifu",
        "Maid",
        "Furry",
        "Shinobi",
        "Ninja",
        "Elf",
        "Human",
        "Orc",
        "Dwarf",
        "Kimono",
        "Badass",
        "Samurai",
        "Bookmark",
        "Powerful",
        "Respected",
        "Brave",
        "Weak",
        "Coward",
        "Cute",
        "Robot",
        "Shirtless",
        "Yakuza",
        "Mafia",
        "Jesus",
        "Witch",
        "Under $1",
        "Under $2",
        "Under $3",
        "Under $4",
        "Under $5",
        "Under $6",
        "Under $7",
        "Under $8",
        "Under $9",
        "Over $10",
        "Over $15",
        "Over $20",
        "Over $25",
        "Over $30",
        "Over $35",
        "Over $40",
        "Over $45",
        "Over $50",
        "Over $60",
        "Over $70",
        "Over $80",
        "Over $90",
        "Over $100",
        "Speedster",
        "Super Hero",
        "Hero",
        "Villain",
        "Ring",
        "Jewelry",
        "Phone Case",
        "Claw Machine",
        "Princess",
        "Prince",
        "Soldier",
        "Cape",
        "Gacha",
        "Board Games",
        "Dragon",
        "Hololive",
        "VTuber",
        "Gawr Gura",
        "Sports",
        "K-Pop",
        "KPop Demon Hunters",
        "New Jeans",
        "BTS",
        "Waldo",
        "Snoopy",
        "John Cena",
        "Randy Orton",
        "The Undertaker",
        "The Rock",
        "Hulk Hogan",
        "Stone Cold Steve Austin",
        "Zombie",
        "Spawn",
        "Hello Kitty",
        "Robin Hood",
        "Hatsune Miku",
        "Vocaloid",
        "DND",
        "Umamusume: Pretty Derby"
    ],
};

// Helper to flatten all scavengerObjects arrays into one array
function getAllScavengerItems() {
    return Object.values(scavengerObjects).flat();
}

// Shuffle function
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
}

function fillBingoCard() {
    const items = getAllScavengerItems();
    shuffle(items);
    let itemIndex = 0;
    for (let i = 0; i < 25; i++) {
        if (i === 12) continue; // skip center
        const cell = document.getElementById('cell-' + i);
        if (cell && itemIndex < items.length) {
            cell.textContent = items[itemIndex++];
        }
    }
}

function getCurrentBingoCard() {
    const card = [];
    for (let i = 0; i < 25; i++) {
        if (i === 12) {
            card.push("FREE");
        } else {
            const cell = document.getElementById('cell-' + i);
            card.push(cell ? cell.textContent : "");
        }
    }
    return card;
}

function renderSavedCard(name, card) {
    const table = document.createElement('table');
    table.className = "saved-bingo-table";
    const tbody = document.createElement('tbody');
    for (let row = 0; row < 5; row++) {
        const tr = document.createElement('tr');
        for (let col = 0; col < 5; col++) {
            const idx = row * 5 + col;
            const td = document.createElement('td');
            td.textContent = card[idx];
            if (idx === 12) {
                td.className = "free-cell";
            }
            tr.appendChild(td);
        }
        tbody.appendChild(tr);
    }
    table.appendChild(tbody);

    const wrapper = document.createElement('div');
    wrapper.className = "saved-card-wrapper";

    // Title and delete button in a row
    const titleRow = document.createElement('div');
    titleRow.className = "saved-card-title-row";

    const title = document.createElement('div');
    title.className = "saved-card-title";
    title.textContent = name ? `Saved by: ${name}` : "Saved Card";

    // Add delete button
    const delBtn = document.createElement('button');
    delBtn.textContent = "Delete";
    delBtn.className = "saved-card-delete-btn";
    delBtn.addEventListener('click', function() {
        wrapper.remove();
    });

    titleRow.appendChild(title);
    titleRow.appendChild(delBtn);

    wrapper.appendChild(titleRow);
    wrapper.appendChild(table);

    document.getElementById('saved-cards').appendChild(wrapper);
}

// this saves the bingo card
document.addEventListener('DOMContentLoaded', function() {
    fillBingoCard();
    document.getElementById('reroll-bingo').addEventListener('click', fillBingoCard);

    document.getElementById('save-bingo').addEventListener('click', function() {
        const name = document.getElementById('player-name').value.trim();
        const card = getCurrentBingoCard();
        renderSavedCard(name, card);
    });
});

// When the prize text is clicked on, it reveals it
document.getElementById('prize-text').onclick = function() {
    this.style.background = 'linear-gradient(90deg, #43cea2, #185a9d)';
    this.innerText = 'First person to get BINGO wins $100 cash!';
};
